import Divisor.Defs
import Divisor.Axioms
import Divisor.PartialFraction
import Divisor.SlopeDist
import Divisor.SupportDisjoint
import Divisor.NormVanish
import Divisor.BassaMonic
import Divisor.CubicIntersection
import Divisor.LogDeriv
import Divisor.ClearedPolyForm
import Divisor.Protocol
import Divisor.Soundness
